### ISSUE TITLE
[FD 5.1] Debug window theme color broken

### ISSUE THREAD

**Issue by DleanJeans** [JoeRobich/fd-vsthemes#5]
This is the window that opens when you hover your mouse over a variable while debugging

![watchwindow](https://cloud.githubusercontent.com/assets/12462089/13349969/b8d329c2-dcaf-11e5-8dad-4df381e42170.png)

**Comment by JoeRobich** [comment]
Thanks so much for taking the time to log this issue. I've seen this myself, but since I use FlashDevelop so rarely these days, I've just ignored it.

I have submitted a pull request to FlashDevelop to fix this issue and hopefully it will be in a nightly build before too long.

You can follow that PR here https://github.com/fdorg/flashdevelop/pull/1309
And find FD development builds here http://flashdevelop.org/downloads/builds/

Thanks
